# Language and env

language: node_js
node_js: 
  - node # latest stable

# What is built

branches:
  only:
  - master

# Travis Lifecycle

install:
  - npm ci

script: npm run build


# Other configs

git:
  depth: 10
